dist: trusty # https://github.com/travis-ci/travis-ci/issues/8863#issuecomment-549759489

services:
  - mysql

language: php

matrix:
  include:
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

install:
  - curl -o config/cacert.pem https://curl.haxx.se/ca/cacert.pem
  - travis_retry composer install --no-interaction --prefer-source
  - mysql -e 'create database oauth;'
  - php cli/dbstorage_create.php

script: vendor/bin/phpunit --configuration phpunit.dist.xml

after_success: bash <(curl -s https://codecov.io/bash)
