language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql

before_install:
  - pip install --user codecov

install:
  - cp config/.env_travis config/.env
  - mysql -e 'create database dbtest;'
  - travis_retry composer install --no-interaction --prefer-source
  - php cli/dbstorage_create.php

script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover clover.xml

after_success:
  - codecov
